### PR TITLE
Added more Python 2/3 portability and XPath support.

### PR DESCRIPTION
**Pull request by wkordalski**
Not tested enough but should work a little.

### CODE REVIEW

**Comment by franekp** [comment]
pagemodel/bsoup.py:19
PageModel.extract_unboxed:
You removed (probably accidentally) catching exception and appending class name to error message.

**Comment by franekp** [comment]
html.py:223
Text.extract:
Why have you removed res.strip() ?

**Comment by franekp** [comment]
html.py:237
Attr.extract:
after removing strip() you should leave a note ("FIXME" or "TODO") that this should be added back after fixing the "Selector.get_attr() returning list sometimes" bug.

**Comment by franekp** [comment]
What is the difference between Fragment and Text classes?

**Comment by franekp** [comment]
lxml.py:23
PageModel.extract_unboxed:
Also catch exceptions and add class name to error messages here.

**Comment by wkordalski** [comment]
`Fragment` returns text with inner tags (so you can get text with all `<b>`, `<i>`, and so on).
As I understand `Text` returns text w/o tags.

**Pull request merged**
